/********************************************************************
 * Copyright (C) 2024 Kaleb Knoettgen
 * All Rights Reserved.
 *
 * Unauthorized reproduction, modification, or distribution of this
 * software is prohibited. Provided "AS IS" without warranty; Kaleb
 * Knoettgen is not liable for any damages arising from its use.
 * All rights not expressly granted are reserved.
 *
 * For more information, visit: www.kalebknoettgen.com
 * Contact: kalebknoettgen@gmail.com
 ********************************************************************/



// =================== OpenAIFunctionLibrary.h ===================

#pragma once

#include "Misc/EngineVersion.h"
#include "CoreMinimal.h"
#include "Kismet/BlueprintFunctionLibrary.h"
#include "AudioMixerBlueprintLibrary.h"
#include "Engine/Texture2D.h"
#include "UObject/NoExportTypes.h"
#include "Templates/Tuple.h"
#include "Http.h"
#include "Runtime/Launch/Resources/Version.h"
#include "GPTChatAPIStructs.h"
#include "JsonObjectConverter.h"
#include "JsonObjectWrapper.h"
#include "Sound/SoundSubmix.h"
#include "Internationalization/Regex.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Sound/SoundWave.h"
#include "AudioDeviceManager.h"
#include "AudioResampler.h"
#include "JsonHttpToolkit.h"
#include "OpenAIFunctionLibrary.generated.h"

// Custom log category
DECLARE_LOG_CATEGORY_EXTERN(AIITKLog, Log, All);

DECLARE_DYNAMIC_DELEGATE_OneParam(FDownloadImageDelegate, UTexture2D*, DownloadedImage);
DECLARE_DYNAMIC_DELEGATE_OneParam(FDisplayNextCharDelegate, const FString&, DisplayedMessage);


UCLASS()
class EZUEGPT_API UOpenAIFunctionLibrary : public UBlueprintFunctionLibrary
{
    GENERATED_BODY()

public:
    // Constructor
    UOpenAIFunctionLibrary();

    // ------------------------
    // Utility Functions
    // ------------------------

    /**
     * Calls a function on the Target object by its name. Similar to the timer function call by name node but... without a timer... you get the idea.
     * @param Target - The object on which to call the function.
     * @param FunctionName - The name of the function to call.
     */
    UFUNCTION(BlueprintCallable, Category = "*AIITK|Utility", meta = (DefaultToSelf = "Target"))
    static void CallFunctionByName(UObject* Target, const FString& FunctionName);

    UFUNCTION(BlueprintPure, Category = "*AIITK|Utility", DisplayName = "Enum To String Array")
    static TArray<FString> Conv_EnumToStringArray(const UEnum* Enum);

    UFUNCTION(BlueprintPure, Category = "*AIITK|Utility", meta = (DisplayName = "String To Enum"))
    static uint8 Conv_StringToEnum(const UEnum* Enum, const FString& StringValue);

    UFUNCTION(BlueprintCallable, Category = "*AIITK|Utility", DisplayName = "Check If Valid JSON")
    static bool IsStringValidJSON(const FString& JSONString);

    UFUNCTION(BlueprintCallable, Category = "*AIITK|Utility", meta = (ToolTip = "Deletes a file at the given FilePath. Use with caution."))
    static bool DeleteFile(FString FilePath);

    UFUNCTION(BlueprintCallable, Category = "*AIITK|Utility")
    static TArray<FString> SimpleRegexSearch(const FString& Pattern, const FString& SearchString, int CaptureGroup);

    UFUNCTION(BlueprintPure, Category = "*AIITK|ChatGPT|JSON|Serialization|Utility", meta = (ToolTip = "Prints the map of string strings"))
    static FString PrintStringMap(const TMap<FString, FString>& InputMap);

    UFUNCTION(BlueprintCallable, Category = "*AIITK|Utility")
    static TMap<FString, FString> ConvertChatCompletionToMap(const FGPTChatCompletion& ChatCompletion);

    UFUNCTION(BlueprintPure, Category = "*AIITK|Utility", DisplayName = "Get Message Content")
    static FString GetMessageContent(const FGPTChatMessage& Message);

    UFUNCTION(BlueprintPure, Category = "*AIITK|Utility", DisplayName = "Get Tool Arguments")
    static TArray<FString> GetToolCallArguments(const FGPTChatMessage& Message);

    // Get message struct from chat completion
    UFUNCTION(BlueprintPure, Category = "*AIITK|Utility", DisplayName = "Get Message From Completion")
    static FGPTChatMessage GetResponseMessage(const FGPTChatCompletion& Completion, const int32 ChoiceIndex);

    /* Gets the value from a function response generated by ChatGPT 
    directly from the completion struct using the supplied argument name. */
    UFUNCTION(BlueprintPure, Category = "*AIITK|Utility", DisplayName = "Get Argument Value From Completion")
    static void GetArgumentFromCompletion(const FGPTChatCompletion& Completion, const FString& ArgumentName, const int32 ChoiceIndex, const int32 ToolCallIndex, FString& OutValue, TArray<FString>& OutArray, bool& bValueFound);

    UFUNCTION(BlueprintPure, Category = "*AIITK|Utility")
    static void GetToolIDFromCompletion(const FGPTChatCompletion& Completion, const int32 ChoiceIndex, const int32 ToolCallIndex, FString& OutValue, bool& bIDFound);

    /* This function brought to you by: +|ADHD|+ 
    Converts FLinearColor to human readable name. Not in scope but it's fun so deal with it...
    I'm talking to myself... */
    UFUNCTION(BlueprintPure, Category = "*AIITK|Utility", DisplayName = "Get Color Name")
    static FString GetColorName(const FLinearColor& Color);


    // ------------------------
    // Audio Functions
    // ------------------------

    UFUNCTION(BlueprintCallable, Category = "*AIITK|Whisper")
    static FString SaveRecordingOutput(UObject* WorldContext, FString FilePath, FString FileName, USoundSubmix* SubmixToRecord);


    // ------------------------
    // Image Processing Functions
    // ------------------------

    UFUNCTION(BlueprintCallable, Category = "*AIITK|DallE|Image Processing", meta = (ToolTip = "Convert a Base64 string to a Texture2D object"))
    static UTexture2D* Base64ToTexture(const FString& Base64String);

    UFUNCTION(BlueprintCallable, Category = "*AIITK|DallE|Image Processing", meta = (ToolTip = "Convert a Texture2D object to a Base64 string"))
    static FString TextureToBase64(UTexture2D* Texture);

    UFUNCTION(BlueprintCallable, Category = "*AIITK|DallE|Image Processing", meta = (ToolTip = "Save a Texture2D object to disk as an image file"))
    static bool SaveTextureToDisk(UTexture2D* Texture, const FString& FileName);

    UFUNCTION(BlueprintCallable, Category = "*AIITK|DallE|Image Processing", meta = (ToolTip = "Load an image file from disk as a Texture2D object"))
    static UTexture2D* LoadTextureFromDisk(const FString& FileName);

    UFUNCTION(BlueprintCallable, Category = "*AIITK|DallE|Image Processing", meta = (ToolTip = "Extract the Base64 string from a Data URL"))
    static FString ExtractBase64FromDataURL(const FString& DataURL);

    UFUNCTION(BlueprintCallable, Category = "*AIITK|DallE|Image Processing", meta = (ToolTip = "Download an image from a URL and return it as a Texture2D object"))
    static void DownloadImageFromURL(const FString& URL, const FDownloadImageDelegate& OnImageDownloaded);

    UFUNCTION(BlueprintPure, Category = "*AIITK|DallE|Image Processing", meta = (ToolTip = "Check if the given URL is valid"))
    static bool IsValidURL(const FString& URL);

    // ------------------------
    // Text Processing Functions
    // ------------------------

    UFUNCTION(BlueprintPure, Category = "*AIITK|Utility", meta = (ToolTip = "Converts a string of text into PascalCase by removing spaces and punctuation, and capitalizing each word"))
    static FString ConvertToPascalCase(const FString& InputString);

    // ------------------------
    // JSON Schema Creation Functions
    // ------------------------

    UFUNCTION(BlueprintPure, Category = "*AIITK|ChatGPT|JSON|Internal", meta = (ToolTip = "Creates a JSON schema for the given field parameters"))
    static FString CreateJSONSchema(EGPTFieldTypes FieldType, const FString& FieldName, const FString& Description, const FString& InputObject, bool bIsArray, bool bRequired, FVector2D ArraySizeConstraints);

    UFUNCTION(BlueprintPure, Category = "*AIITK|ChatGPT|JSON|Internal", meta = (ToolTip = "Creates a JSON schema for an object array with the given field parameters"))
    static FString CreateJSONSchemaForObjectArray(const FString& FieldName, const FString& Description, const TArray<FString>& InputObject, bool bIsArray, bool bRequired, FVector2D ArraySizeConstraints);

    UFUNCTION(BlueprintPure, Category = "*AIITK|ChatGPT|JSON|Internal", meta = (ToolTip = "Creates a JSON schema for an enum with the given parameters"))
    static FString CreateJSONSchemaForEnum(const FString& FieldName, const FString& Description, EJsonEnumType EnumType, const TArray<FString>& EnumValues, bool bIsArray, bool bRequired, FVector2D ArraySizeConstraints);

    // ------------------------
    // JSON Serialization Functions
    // ------------------------

    UFUNCTION(BlueprintPure, Category = "*AIITK|ChatGPT|JSON|Serialization", meta = (ToolTip = "Serializes an FBaseObject to a JSON object"))
    static FString SerializeBaseObject(const FBaseObject& Obj);

    UFUNCTION(BlueprintPure, Category = "*AIITK|ChatGPT|JSON|Serialization", meta = (ToolTip = "Serializes an FGPTChatFunction to a JSON object", CallInEditor = "true"))
    static FString SerializeGPTChatFunction(const FGPTChatFunction& Function);

    // ------------------------
    // JSON Parsing Functions
    // ------------------------

    UFUNCTION(BlueprintCallable, Category = "*AIITK|ChatGPT|JSON|Parsing", meta = (ToolTip = "Parses arguments from API response into a map"))
    static TMap<FString, FString> ParseFunctionArguments(const FString& JsonString, bool bEncodeArrayValues);

    UFUNCTION(BlueprintPure, Category = "*AIITK|ChatGPT|JSON|Parsing", meta = (ToolTip = "Retrieve argument value from the map"))
    static void RetrieveArgumentValue(const TMap<FString, FString>& InputMap, const FString& Key, FString& OutValue, TArray<FString>& OutArray, bool& bValueFound);

    // ------------------------
    // Chat Management Functions
    // ------------------------

    // Function to calculate total token count of a conversation based on FGPTChatMessage
    UFUNCTION(BlueprintCallable, Category = "*AIITK|ChatGPT|ManageChat")
    static int CalculateConversationTokens(const TArray<FGPTChatMessage>& Messages);

    // Function to truncate a conversation based on token count and FGPTChatMessage
    UFUNCTION(BlueprintCallable, Category = "*AIITK|ChatGPT|ManageChat", meta = (DisplayName = "Truncate Conversation"))
    static TArray<FGPTChatMessage> TruncateConversation(TArray<FGPTChatMessage> Conversation, int MaxTokens);

    // ------------------------
    // 11Labs Parsing Functions
    // ------------------------

    UFUNCTION(BlueprintPure, Category = "*AIITK|11Labs|Parsing", meta = (ToolTip = "Convert voices array into a tmap for easy parsing"))
    static TMap<FString, FString> ConvertVoiceArrayToMap(const TArray<FVoiceInfo>& VoicesArray);

    UFUNCTION(BlueprintPure, Category = "*AIITK|11Labs|Parsing", meta = (ToolTip = "Convert model array into a tmap for easy parsing"))
    static TMap<FString, FString> ConvertModelArrayToMap(const TArray<FModelInfo>& ModelsArray);

    // ------------------------
    // Internal Utility Functions
    // ------------------------

    template<typename TEnum>
    static FString GetEnumValueAsString(const FString& Name, TEnum Value);

    static FString EnumFieldTypeToString(const EJsonEnumType& EnumType);

    static FString GetRoleAsString(EGPTRole Role);

    static FString SerializeField(const EGPTFieldTypes& FieldType, const EJsonEnumType EnumFieldType, const TArray<FString> EnumValues, const FString& Description, bool bIsRequired, bool bIsArray, FVector2D ArraySizeConstraints, TSharedPtr<FJsonObject> NestedProperties);

    static FString FieldTypeEnumToString(const EGPTFieldTypes& FieldType);

    static FString ImageSizeToString(EImageSize ImageSize);

    static FString ResponseFormatToString(EGPTResponseFormat ResponseFormat);

    UFUNCTION(BlueprintPure, Category = "*AIITK|11Labs|Parsing", meta = (ToolTip = "Output format enum as sample rate int32"))
    static int32 OutputFormatToSampleRate(EOutputFormat OutputFormat);

    UFUNCTION(BlueprintPure, Category = "*AIITK|11Labs|Parsing", meta = (ToolTip = "Output format enum as sample rate string"))
    static FString OutputFormatEnumToString(EOutputFormat OutputFormat);

    UFUNCTION(BlueprintPure, Category = "*AIITK|11Labs|Parsing", meta = (ToolTip = "Converts audio file format enum to string"))
    static FString AudioFileFormatEnumToString(EAudioFileFormat AudioFileFormat);



    static TSharedPtr<FJsonObject> CreateLogitBiasObject(const TMap<int32, float>& LogitBiasMap);

    static TArray<TSharedPtr<FJsonValue>> CreateFunctionsArrayForAPI(const TArray<FGPTChatFunction>& Functions);

    static FString HandleJsonArray(const TArray<TSharedPtr<FJsonValue>>& JsonArray);

    static void ParseFunctionArgumentsRecursive(TSharedPtr<FJsonObject> JsonObject, const FString& ArgumentToFind, TMap<FString, FString>& FunctionArguments, FString& FoundArgumentValue);

    static void ParseArgumentsFromJsonObject(TSharedPtr<FJsonObject> JsonObject, TMap<FString, FString>& OutMap, const FString& ParentKey);

    // Helper function to calculate the number of tokens in a FGPTChatMessage, APPROXIMATION
    static int CalculateTokens(const FGPTChatMessage& Message);

    //UFUNCTION(BlueprintPure, Category = "*AIITK|ChatGPT|Serialization", meta = (ToolTip = "Serializes an FObjectLevel3 to a JSON object"))
    static FString SerializeObjectLevel3(const FObjectLevel3& Obj);

    //UFUNCTION(BlueprintPure, Category = "*AIITK|ChatGPT|Serialization", meta = (ToolTip = "Serializes an FObjectLevel2 to a JSON object"))
    static FString SerializeObjectLevel2(const FObjectLevel2& Obj);

    //UFUNCTION(BlueprintPure, Category = "*AIITK|ChatGPT|Serialization", meta = (ToolTip = "Serializes an FObjectLevel1 to a JSON object"))
    static FString SerializeObjectLevel1(const FObjectLevel1& Obj);

    private:
    
    static void HandleImageDownloadResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FDownloadImageDelegate OnImageDownloaded);
};